### ISSUE TITLE
Provide rationale for link inclusion

### ISSUE THREAD

**Issue by VictorNicollet** [MaximAbramchuck/awesome-interviews#14]
According to the Awesome manifesto: 

> Apart from suggesting a particular item on your list, you should also inform your readers why it's on the list and how they will benefit from it.

None of the links seem to carry an explanation of why they are included in an _awesome_ list.

**Comment by MaximAbramchuck** [comment]
I'm currently working on this.



With best regards, Maxim Abramchuk.

**Comment by MaximAbramchuck** [comment]
Added descriptions for all the links.
