### ISSUE TITLE
Segmentation by language

### ISSUE THREAD

**Issue by pcottle** [MaximAbramchuck/awesome-interviews#15]
Why the segmentation of these questions by language? Most big tech companies at least interview in whatever language the candidate prefers, or in pseudo-code if necessary. Its an emphasis on algorithms and data structures, not language details.

**Comment by MaximAbramchuck** [comment]
@pcottle big rework of all the list is coming soon :)

**Comment by pcottle** [comment]
Sweet!

On Tue, Dec 1, 2015 at 11:52 AM, Maxim Abramchuk <notifications@github.com>
wrote:

> @pcottle <https://github.com/pcottle> big rework of all the list is
> coming soon :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MaximAbramchuck/awesome-interviews/issues/15#issuecomment-161076796>
> .
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Comment by MaximAbramchuck** [comment]
@pcottle rework is already merged. thanks for your contribution! if you have some other ideas it's time to submit a PR ;)

**Comment by pcottle** [comment]
Great! Much better
