### ISSUE TITLE
No C# questions?

### ISSUE THREAD

**Issue by Superbest** [MaximAbramchuck/awesome-interviews#20]
I see that there's no C# or .NET section. Is this because .NET developers do not even have to answer interview questions? :-)

**Comment by MaximAbramchuck** [comment]
@Superbest I'm going to do a huge rework of my repo
1) Add description for each the link.
2) Add programming languages, algorithms, patterns, etc. sections
3) Add a lot more stuff like, C#, .NET, different popular frameworks and etc.

**Comment by MaximAbramchuck** [comment]
Added C# and .NET questions in a new version.
