### ISSUE TITLE
Algorithm questions

### ISSUE THREAD

**Issue by Superbest** [MaximAbramchuck/awesome-interviews#21]
I see that there is a "Design patterns" section, but no "Algorithm" section. It seems that questions such as "propose an algorithm to solve task X, implement it in pseudocode/language of your choice" are quite common.

Here is one example that I recently came across: https://www.shiftedup.com/2015/05/07/five-programming-problems-every-software-engineer-should-be-able-to-solve-in-less-than-1-hour

I actually wrote Python solutions to Santiago's questions, I wouldn't mind adding them to my github when I have time. But this sort of question is possibly the single most common class I've heard about. Is it worth adding it as a section in this repo?

**Comment by MaximAbramchuck** [comment]
@Superbest sure, I'm going to do a great rework of my repo
1) Add description for each the link.
2) Add programming languages, algorithms, patterns, etc. sections

**Comment by EvgenyKarkan** [comment]
Hello @MaximAbramchuck, take a look at my repo with Objective-C algorithms https://github.com/EvgenyKarkan/EKAlgorithms
I hope you will find It useful for iOS stuff.

**Comment by MaximAbramchuck** [comment]
@Superbest added, merged.
@EvgenyKarkan added, merged.
Thanks for your contribution!
