### ISSUE TITLE
Backed interview questions

### ISSUE THREAD

**Issue by starandtina** [MaximAbramchuck/awesome-interviews#22]
@MaximAbramchuck , I have ever set up a curated list of backend interview questions, including:

 - General Questions/Ice Breaker
 - Algos, Data Structures, & Computer Science Fundamentals Questions 
 - Design Questions
 - Backend Linux Questions
 - Management Questions

Please refer to [backend-interview-questions](https://github.com/starandtina/backend-interview-questions).

I don't know where can I put? Do you have an idea about it? Or you think it's necessary to split it into smaller parts? 

-zx

**Comment by MaximAbramchuck** [comment]
@starandtina I'm going to do a huge rework of my repo
1) Add description for each the link.
2) Add programming languages, algorithms, patterns, etc. sections
3) Add a lot more stuff like, C#, .NET, different popular frameworks and etc.

So, I'll merge it into a new version I think.

**Comment by starandtina** [comment]
@MaximAbramchuck Thanks for your explanation.
