### ISSUE TITLE
Trim down

### ISSUE THREAD

**Issue by ricardobeat** [MaximAbramchuck/awesome-interviews#37]
How curated is this list? Many of the links have spammy titles and low-quality content.  The javascript section is almost a straight copy-paste from google results. Take this one:

[JavaScript Interview Questions have been designed specially to get you acquainted with the nature of questions you may encounter during your interview for the subject of JavaScript ](http://www.tutorialspoint.com/javascript/javascript_interview_questions.htm)

Not only is it outdated, but contains non-sense: *JavaScript is complementary to and integrated with Java*.

This list would be much more useful with some editorializing. Considering how popular this project got it's also important to link to correct content. Would you accept a PR removing/replacing multiple links at once?

**Comment by MaximAbramchuck** [comment]
@ricardobeat As you understand, I can't be an expert in all the programming languages and all the areas. So, sure, bad or outdated lists can be found here.
So, I really ask community to help me improving this awesome lists.
>Would you accept a PR removing/replacing multiple links at once?
Sure, you are welcome!
