### ISSUE TITLE
Add to @sindresorhus's Awesome repo

### ISSUE THREAD

**Issue by AllThingsSmitty** [MaximAbramchuck/awesome-interviews#39]
You should submit a PR to [Awesome](https://github.com/sindresorhus/awesome) to include your list. :sunglasses:

**Comment by MaximAbramchuck** [comment]
https://github.com/sindresorhus/awesome/pull/430
@AllThingsSmitty I've already tried, but I think I'll wait one more week :)

**Comment by AllThingsSmitty** [comment]
K, good luck! :+1:
