### ISSUE TITLE
Sort each category alphabetically..

### ISSUE THREAD

**Issue by lipis** [MaximAbramchuck/awesome-interviews#50]
It's very arbitrary anyway.. so at least it will be easier to scan if you know what you're looking for..

**Comment by MaximAbramchuck** [comment]
@lipis if you have some automated tools to do this, you're welcome :)

**Comment by lipis** [comment]
using Sublime.. you can simply select each group and then F5 to sort them... I've done it once already #18.. and not willing to do it again :/
